OAuth implementation
CactusBot/CactusBot pull request #226
Opened 2017-03-03 18:05 UTC by Innectic

Fixes #225

2017-03-03 18:13 UTC, 2Cubed requested changes

2017-03-03 18:13 UTC, 2Cubed commented on cactusbot/cactus.py
> -    async def run(self, api, *auth):
This should stay as `*auth` - remember, service agnostic. (Discord needs two parameters, for example.)

2017-03-03 18:13 UTC, 2Cubed commented on cactusbot/cactus.py
> +    async def run(self, api, token):
Where is `token` actually going? Doesn't look like it's being used... o.O

2017-03-03 18:13 UTC, 2Cubed commented on cactusbot/handler.py
> +    async def register_handler(self, handler):
This won't work; `handlers` is a `tuple`, and you're trying to `+=` something to it. (Test your code! >.>)

What might be better is to just make `self.handlers = list(handlers)` in `__init__`, and then just use `handlers.handlers.append(new_handler_thing)`.

2017-03-03 18:13 UTC, 2Cubed commented on caches/followers.json
> +}
\>.>

2017-03-03 18:13 UTC, 2Cubed commented on cactusbot/handlers/respond.py
> +        print(packet.json)
<.<

2017-03-03 18:20 UTC, Innectic commented on cactusbot/handler.py
> +    async def register_handler(self, handler):
I forgot to remove that, it's not actually being used. I thought of that while I was writing that, and changed it to an event.

2017-03-03 18:20 UTC, Innectic commented on caches/followers.json
> +}
Added this to the gitignore ;P

2017-03-03 20:01 UTC, 2Cubed approved these changes

2017-03-03 20:55 UTC, merged

2017-03-04 22:34 UTC, ProbablePrime reviewed
ya thatll do for now

2017-03-05 02:18 UTC, 2Cubed commented
@ProbablePrime Awesome. Will this be changing, though?

2017-03-06 02:11 UTC, ProbablePrime commented
No changes will affect this, implicit oauth here to stay